### ISSUE TITLE
illegal yaml file - threat_emotet_excel_regsvr32_execution.yml

### ISSUE THREAD

**Issue by levh** [mbabinski/Sigma-Rules#2]
the next file is not a legal yaml file by a lot of online yaml validator which means that open the file as yaml fail.
the problem seems to be in the first line that contain multiple ":"

**Comment by mbabinski** [comment]
Thanks for the fix! I've fixed this and other issues with the files in [8592515](https://github.com/mbabinski/Sigma-Rules/commit/8592515ace68c98b454ae336afce80101fae5bb5).
